# Generated by Django 6.0.3 on 2026-04-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['employee_code']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employee_profiles',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
