# Generated by Django 6.0.3 on 2026-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
