# Generated by Django 6.0.3 on 2026-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Attendance System', max_length=150)),
                ('default_timezone', models.CharField(default='Asia/Manila', max_length=64)),
                ('lunch_minutes_allowed', models.PositiveIntegerField(default=60)),
                ('break_minutes_allowed', models.PositiveIntegerField(default=15)),
                ('bio_minutes_allowed', models.PositiveIntegerField(default=10)),
                ('late_after_time', models.TimeField(blank=True, null=True)),
                ('overbreak_grace_minutes', models.PositiveIntegerField(default=0)),
                ('allow_employee_log_edit', models.BooleanField(default=False)),
                ('allow_admin_log_edit', models.BooleanField(default=True)),
                ('allow_duplicate_tags', models.BooleanField(default=False)),
                ('require_work_mode_on_time_in', models.BooleanField(default=True)),
                ('allow_multiple_tag_clicks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
