# Generated by Django 6.0.3 on 2026-04-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_alter_systemsetting_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='required_work_minutes',
            field=models.PositiveIntegerField(default=480),
        ),
    ]
