# Generated by Django 6.0.3 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting_late_grace_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='time_in_cooldown_hours',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
