# Generated by Django 6.0.3 on 2026-04-11 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SHIFT', 'Shift'), ('LUNCH', 'Lunch'), ('BREAK', 'Break'), ('BIO', 'Bio')], max_length=20)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('default_allowed_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TagLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('work_mode', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('ADMIN', 'Admin'), ('CORRECTION', 'Correction'), ('SYSTEM', 'System')], default='WEB', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tag_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_logs', to=settings.AUTH_USER_MODEL)),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='tagging.tagtype')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
