# Generated by Django 6.0.3 on 2026-04-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taglog',
            table='tag_logs',
        ),
        migrations.AlterModelTable(
            name='tagtype',
            table='tag_types',
        ),
    ]
