# Generated by Django 6.0.3 on 2026-04-15 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('BRAND_NEW', 'Brand New'), ('USED', 'Used'), ('UNUSED', 'Unused'), ('DEFECTIVE', 'Defective'), ('TO_BE_CHECKED', 'To Be Checked')], default='UNUSED', max_length=20)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_equipment',
                'ordering': ['asset_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'is_supervisor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='inventory.inventoryuser')),
            ],
            options={
                'db_table': 'inventory_users',
                'ordering': ['full_name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.equipment')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_history', to='inventory.inventoryuser')),
            ],
            options={
                'db_table': 'equipment_assignments',
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_equipment', to='inventory.inventoryuser'),
        ),
    ]
