# Generated by Django 6.0.3 on 2026-04-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_can_use_queueing_user_can_access_queueing'),
        ('inventory', '0003_inventoryauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_employees', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_equipment', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_equipment_assignments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_equipment_categories', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='equipmenthistorylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_equipment_history_logs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='inventoryauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs_scope', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_supervisors', to='accounts.company'),
        ),
    ]
