# Generated by Django 6.0.3 on 2026-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0005_queuecounter_assigned_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
    ]
