# Generated by Django 6.0.3 on 2026-04-11 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('first_time_in', models.DateTimeField(blank=True, null=True)),
                ('last_time_out', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('WORKING', 'Working'), ('LUNCH', 'Lunch'), ('BREAK', 'Break'), ('BIO', 'Bio')], default='OFF_DUTY', max_length=20)),
                ('work_mode', models.CharField(blank=True, max_length=10)),
                ('timezone_at_log', models.CharField(default='Asia/Manila', max_length=64)),
                ('total_work_minutes', models.PositiveIntegerField(default=0)),
                ('total_late_minutes', models.PositiveIntegerField(default=0)),
                ('is_late', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', 'employee_id'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('MISSING_TAG', 'Missing Tag'), ('EDIT_LOG', 'Edit Log'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('target_work_date', models.DateField()),
                ('details', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='attendance.attendancesession')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverbreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('allowed_minutes', models.PositiveIntegerField()),
                ('actual_minutes', models.PositiveIntegerField()),
                ('excess_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('WAIVED', 'Waived')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overbreak_records', to='attendance.attendancesession')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overbreak_records', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_overbreaks', to=settings.AUTH_USER_MODEL)),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overbreak_records', to='tagging.tagtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
