# Generated by Django 6.0.3 on 2026-04-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendancesession',
            table='attendance_sessions',
        ),
        migrations.AlterModelTable(
            name='correctionrequest',
            table='correction_requests',
        ),
        migrations.AlterModelTable(
            name='overbreakrecord',
            table='overbreak_records',
        ),
    ]
