# Generated by Django 6.0.3 on 2026-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancesession_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='has_incomplete_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='missing_tag_pairs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='summary_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='total_bio_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='total_break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='total_lunch_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='total_overbreak_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
