# Generated by Django 6.0.3 on 2026-04-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_has_incomplete_records_and_more'),
        ('tagging', '0002_alter_taglog_table_alter_tagtype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequest',
            name='applied_tag_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='tagging.taglog'),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='requested_tag_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='tagging.tagtype'),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='requested_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='requested_work_mode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
