# Generated by Django 6.0.3 on 2026-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_correctionrequest_applied_tag_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequest',
            name='action_type',
            field=models.CharField(choices=[('CHANGE', 'Change'), ('REMOVE', 'Remove'), ('SHIFT_CHANGE', 'Shift Change')], default='CHANGE', max_length=20),
        ),
    ]
